spring:
  application:
    name: users-module

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true