spring:
  application:
    name: product-module
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: on
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl